# -*- coding: utf-8 -*-
"""Willkommen bei Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# CC6: WEATHER DATA LOOP DOWNLOAD
import requests
import json
import pandas as pd
import time

# City coordinates
weatherCities = [
    {"name": "Cape_Town", "lat": -33.92, "lon": 18.42},
    {"name": "Los_Angeles", "lat": 34.05, "lon": -118.24},
    {"name": "London", "lat": 51.51, "lon": -0.13},
    {"name": "Tokyo", "lat": 35.68, "lon": 139.65},
    {"name": "Sydney", "lat": -33.87, "lon": 151.21},
    {"name": "Rio_de_Janeiro", "lat": -22.91, "lon": -43.17}
]

# API base URL and base filename
url_base = "https://archive-api.open-meteo.com/v1/archive?latitude={}&longitude={}&start_date=1950-01-01&end_date=2025-12-31&daily=temperature_2m_max,temperature_2m_min&timezone=auto"
file_base = "weather_{}.json"

# Loop
for city in weatherCities:
    URL = url_base.format(city['lat'], city['lon'])
    try:
        response = requests.get(URL)
        data = response.json()

        # Check if there is data and wheather API call limit is already reached
        if 'daily' not in data:
            print(f"✗ No data available for {city['name']}")
            print(f"  API response: {data}")
            continue

        # Extract daily data & convert to DataFrame
        daily_data = data['daily']
        df = pd.DataFrame({
            'date': pd.to_datetime(daily_data['time']),
            'temp_max': daily_data['temperature_2m_max'],
            'temp_min': daily_data['temperature_2m_min']
        })

        # Aggregate to yearly -> better for visualisation
        df['year'] = df['date'].dt.year
        yearly_df = df.groupby(['year']).agg({
            'temp_max': 'max',
            'temp_min': 'min'
        }).reset_index()
        yearly_df['date'] = pd.to_datetime(yearly_df['year'].astype(str) + '-01-01')

        # Output format
        yearly_df = yearly_df[['date', 'temp_max', 'temp_min']]
        yearly_df['date'] = yearly_df['date'].dt.strftime('%Y-%m-%d')

        # Structure data
        output_data = {
            'city': city['name'].replace('_', ' '),
            'latitude': city['lat'],
            'longitude': city['lon'],
            'data': yearly_df.to_dict('records')
        }

        # Filename
        fileName = file_base.format(city['name'].lower())

        # Save JSON
        with open(fileName, 'w', encoding='utf-8') as f:
            json.dump(output_data, f, ensure_ascii=False, indent=4)

    except Exception as e:
        print(f"Error processing {city['name']}: {str(e)}")
        continue