# -*- coding: utf-8 -*-
"""Willkommen bei Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

# 1. Load the Wales boundary TopoJSON
wales_url = "https://raw.githubusercontent.com/jhellingsdata/RADataHub/refs/heads/main/MappingWorkshop/geo_data/LAD_WLS_2025_05.topojson"
wales = gpd.read_file(wales_url)

# 2. Set CRS for Wales if it doesn't have one
if wales.crs is None:
    wales = wales.set_crs("EPSG:4326")
else:
    wales = wales.to_crs("EPSG:4326")

print(f"Wales CRS: {wales.crs}")

# 3. Load your pub coordinates CSV
pubs_df = pd.read_csv("https://raw.githubusercontent.com/SofieWied/SofieWied.github.io/refs/heads/main/cc7_pub_coordinates_uk.csv")

# 4. Convert pub coordinates to geometry points
geometry = [Point(lon, lat) for lon, lat in zip(pubs_df['longitude'], pubs_df['latitude'])]

# 5. Create GeoDataFrame with explicit CRS
pubs_gdf = gpd.GeoDataFrame(
    pubs_df,
    geometry=geometry,
    crs="EPSG:4326"
)

print(f"Pubs CRS: {pubs_gdf.crs}")

# 6. Combine all Wales polygons into one boundary
wales_boundary = wales.geometry.unary_union

# 7. Filter pubs that are within Wales
pubs_gdf['in_wales'] = pubs_gdf.geometry.apply(lambda x: wales_boundary.contains(x))
pubs_in_wales = pubs_gdf[pubs_gdf['in_wales'] == True]

# 8. Keep only coordinates
pubs_filtered = pubs_in_wales[['latitude', 'longitude']].copy()

# 9. Save to CSV
pubs_filtered.to_csv('wales_pubs_filtered.csv', index=False)

print(f"Original pubs: {len(pubs_df)}")
print(f"Pubs in Wales: {len(pubs_filtered)}")